### ISSUE TITLE
Plan for architecture

### ISSUE THREAD

**Issue by crthpl** [vlang/go2v#1]
There are two ways this could be done:
1. The way I did in [crthpl/go2v](https://github.com/crthpl/go2v): Pure go; write the V output to a string builder and then write that to a file.
2. In go, get the AST and output the json to stdout, or possibly make it a shared library and use it like that (headers will be needed though), and then in V convert that to a V AST and then vfmt it, or write it directly to a strings builder (latter would have more duplicated code).
3. There might be a different way I hadn't though of. 

I vote 2

What do you think? @medvednikov

**Comment by JalonSolov** [comment]
What do you mean by "headers will be needed though"?

Otherwise, I vote for #2 as well.  At least until go2v can convert Go itself, and we can do it _all_ in V.  :-)

**Comment by crthpl** [comment]
@JalonSolov If we make the go part a shared library, V will need to know all the struct definitions so that it knows what a go AST looks like

**Comment by JalonSolov** [comment]
Ah.  I don't think of that as needing headers.  Just need structs to decode the JSON into.

**Comment by Hunam6** [comment]
I think that can be closed as the plan is pretty much well defined in [DESIGN.md](https://github.com/vlang/go2v/blob/main/DESIGN.md). Further discussions can take place on Discord.
