### ISSUE TITLE
`-o` outputs in the wrong directory

### ISSUE THREAD

**Issue by Hunam6** [vlang/go2v#13]
`go2v file.go -o out.v` should put `out.v` in the same directory as `file.go`, just as `go2v file.go` would do.

**Comment by JalonSolov** [comment]
It works that way for me:
```
$ v run git/go2v foo.go -o foo.v
$ ls foo*
foo.go  foo.v
$
```

**Comment by Hunam6** [comment]
Pretty sure you're the best placed for this @JalonSolov

**Comment by JalonSolov** [comment]
How does it fail for you?  And on what os?

**Comment by Hunam6** [comment]
When I'm on project root and I do `v run go2v.v tests/const/const.go -o const.vv` it doesn't work the way it's intended

**Comment by JalonSolov** [comment]
Aha!  Ok, I think I know what's going on.

**Comment by Hunam6** [comment]
Nice !

**Comment by JalonSolov** [comment]
Ok, maybe not.  On Linux, it works.  Are you sure you've updated to latest source?  :-)
```
$ pwd
/home/jamie/git/go2v
$ ls foo*
ls: cannot access 'foo*': No such file or directory
$ v run . ~/foo.go -o foo.v
$ ls foo*
foo.v
$ 
```

**Comment by JalonSolov** [comment]
Ok, you don't want the .v file to go to the current directory, you want it to go to the same directory as the go source file.

That's actually something I changed on purpose.

If you use `-o`, you are telling it _exactly_ where to put the output file.  If you don't specify `-o`, it will put it where you expected.  The main difference I see is that you're trying to change the file extension.

Perhaps we can come up with a compromise... or maybe a new flag to tell it to change the name but put it in the same dir as the go source.

**Comment by Hunam6** [comment]
Mhh I see..

Maybe one more flag, like `-ro` for `relative output` or... I don't know we have to find a name, a meaningful name, a meaningful for everyone name

**Comment by Hunam6** [comment]
OR, keep one flag, and if you want to output to the same directory as the go source file you do `-o abc.v` and it you want to be from the executable directory you do `-o ./abc.v`

What do you think?

**Comment by JalonSolov** [comment]
It might make more sense to use `-output-path` and `-output-file`, but if you wanted to override both, you might have to use both.  :-\

As the code is now, you can do `go2v tests/const/const.go -o tests/const/const.vv` and it will work the way you were thinking.

Basically, `-o` is usually meant to be an override for where something is put, if there's a default, and it it is usually expected to be a path, not just a filename.  However, go2v doesn't have to do it that way, as long as we document what it really does.

**Comment by Hunam6** [comment]
To overwrite both you could just `./path/to/dir/file_name.v`, ohh I see your point it won't work for a file without extension, it can't guess what if it's a folder or a file? Can you confirm this?

> However, go2v doesn't have to do it that way, as long as we document what it really does.

I agree, whatever we decide let's remember this

**Comment by JalonSolov** [comment]
That could work... if none of the path exists, it can check for an extension (the .v part), and know that you want to create the path and put the .v file in it.

The only problem would be if you put `path/to/foo` and meant it to be a file named `foo`... there would be no way to tell that just from what was typed in.  It that case it would create `path/to/foo/file_name.v`.

**Comment by Hunam6** [comment]
Yes that may be the solution, I don't even see a situation where you want your output to be specifically without extension; the only situation I see is when you quickly want to specify a custom output, maybe to keep your last output that had the default name, and so, in this situation you don't want to specify a folder.

**Comment by JalonSolov** [comment]
Custom output directory is a good idea - then you can keep the translated .v files separate from the .go files.  Makes it easier to wipe out all the translated files (just `rm -rf output_dir`), etc.  It's a very special case to output with a different extension, but that is simple enough by giving the full path including the filename with the new extension (that works right now).

I think what we need is an explicit table of what options cause what output.  Here's what we have right now:

| Options                       | Output                               |
| ----------------------------- | ---------------------------------- |
| file.go                          | file.v in same dir as file.go |
| file.go -o file.vv            | file.vv in current dir            |
| file.go -o foo/file.vv      | file.vv in `foo` dir               |
| dir with .go files           | `out` dir with .v files           |
| dir with .go files -o foo | `foo` dir with .v files           |

**Comment by Hunam6** [comment]
I have a new idea, let's restart from the beginning, why did I do that* and why do I need that*? Because when crafting and testing the tests I need to be able to quickly generate `.vv` files.

`go2v` already have the test command, it currently takes no options expect an argument (`-compact`).
Why not make it able to run only one test like so: `go2v test function_complex` & with the argument `-c` (for create) it creates the `.vv` file, like so: `go2v test -c function_complex`?

As you said, it's a very specific problem to be able to change the extension, consequently a very specific solution is needed.

*it outputs in the same directory as the go source file with the `-o` argument

**Comment by JalonSolov** [comment]
Let's review the way V normally does things... if you have `foo.v`, you can also put `foo_test.v` in the same directory.  Go does the same thing.  V's `foo_test.vv` files normally go in a separate directory, along with matching `.out` files.  Should go2v use the same scheme, so it is more familiar to V programmers?

**Comment by JalonSolov** [comment]
Actually, Alex said this on discord...
```
vv files are weird
I regret creating this extension 🙂
just complicates things
```
:-)

https://discord.com/channels/592103645835821068/592320321995014154/879724200699514910

**Comment by Hunam6** [comment]
Yes but we don't really have the choice, at least if we want to make tiny tests that ensures that when something breaks it'll not be a mess to debug

**Comment by JalonSolov** [comment]
Agreed - we want _some_ sort of regression testing to make sure things don't break.

Question:  What does a new option buy, other than possibly making the commands shorter, over what is there now?

`go2v test/const/const.go -o test/const/const.vv` will work now.  It does require specifying the path twice, but that could likely be done with copy/paste.

`go2v test -c test/const/const.go` doesn't repeat the path, but it will take adding some code to support the new option.

So the question is:  Is it worth adding the extra code?

**Comment by Hunam6** [comment]
Oh sorry I didn't saw this message

> Let's review the way V normally does things... if you have foo.v, you can also put foo_test.v in the same directory. Go does the same thing. V's foo_test.vv files normally go in a separate directory, along with matching .out files. Should go2v use the same scheme, so it is more familiar to V programmers?

I really think tests are really well organised, using _test files would be a mess and involve duplicate files. To prove that, @KeitoTobi1 [wasn't able to implement enums support](https://github.com/vlang/go2v/issues/7) but they [managed to to implement a test](https://github.com/vlang/go2v/pull/6).

> go2v test -c test/const/const.go doesn't repeat the path, but it will take adding some code to support the new option.

I was thinking more about something like 
`go2v test -ct const` (for create test) to create the dir `const` with the file `const.go` in it
`go2v test -co const` (for create output) to create the corresponding `const.vv` file

> Is it worth adding the extra code?

Yes as:
- It'll not affect performance
- It'll not be a breaking change
- It'll facilitate the job for someone willing to improve the tool by implementing functionality, because you have to test things a lot sometimes
- I'll dev a personal tool for this anyway because it's really useful/it's a time saver, to debug and improve the tool, so why not give it directly to the community?

**Comment by JalonSolov** [comment]
How can `go2v test -ct const` work?  Will the code be smart enough to create a `const.go` file for you?  :-)  Otherwise, it will either only create the directory (same as `mkdir tests/const`), or you'll also have to supply the path to the .go file to put in the directory.  I suppose it could create a "dummy" `const.go` file that only had `package main` at the top...

I am not against adding code if it is going to be useful to have.  I just hate wasting my time writing extra code that might only be used once or twice.

**Comment by Hunam6** [comment]
> How can go2v test -ct const work? Will the code be smart enough to create a const.go file for you? :-) Otherwise, it will either only create the directory (same as mkdir tests/const), or you'll also have to supply the path to the .go file to put in the directory. I suppose it could create a "dummy" const.go file that only had package main at the top...

Yes it'll create a dummy file just like described it.

> I am not against adding code if it is going to be useful to have. I just hate wasting my time writing extra code that might only be used once or twice.

I'll be used absolutely every time someone wants to implement a new feature, and to ensure it's really used, we could create a CONTRIBUTING.md file with instruction on how to add a feature and also simplify the command, it needs to be simple and engaging.
I suggest
`go2v test create <name>` to create the dir and the dummy file
and
`go2v test out <name>` or `go2v test test <name>` to create the .vv file

**Comment by JalonSolov** [comment]
Alright, I'll see what I can do.  I've never used the `cli` module before, so this will give me a chance to figure it out.

**Comment by Hunam6** [comment]
> Alright, I'll see what I can do.  I've never used the `cli` module before, so this will give me a chance to figure it out.

Oh don't feel required to do this change, if you don't want to I'll do it, no problem 🙂
