### ISSUE TITLE
`go2v test -out <name>` doesn't generate the good code

### ISSUE THREAD

**Issue by Hunam6** [vlang/go2v#19]
I'll always generate the following code, regardless of the inputed file name

```v
module 

```

I'm pretty sure that the reason of that is that the inputed file is wrongly get, because the output above is the output go2v gives when supplied with an empty file.

**Comment by JalonSolov** [comment]
Can't reproduce...
```
$ v run ~/git/go2v import.go
$ ls
import.go  import.v  import.vv  out.vv
$ cat import.go
package main

import (
        "fmt"
        "io"
)$
$ cat import.v
module main

import fmt
import io
$ 
```
