### ISSUE TITLE
go2v accepts .v files as input

### ISSUE THREAD

**Issue by JalonSolov** [vlang/go2v#25]
Try `go2v all_test.v` - it creates `all_tes.v` with a single line with `module` on it.

Need to add an error check in case the input file cannot be parsed as a valid .go file.

**Comment by Hunam6** [comment]
Do you mean doing it by the extension or if get_ast.go fails?

**Comment by JalonSolov** [comment]
Could do both.  If a file is given, it could reject it if the name doesn't end with `.go`.  get_ast.go should _also_ fail if the .go file is not valid go.

The change must be made in get_ast.go whether the extension check is done first or not, in case the input is a directory with bad .go files in it.

**Comment by Hunam6** [comment]
Okay, once you managed to fix https://github.com/vlang/go2v/pull/24 I'll write a PR
