### ISSUE TITLE
unexpected token `&`, expecting name

### ISSUE THREAD

**Issue by Thihup** [vlang/go2v#69]
When trying to convert the [Jacobin project](https://github.com/platypusguy/jacobin), we get the following error:

```shell
➜ /workspaces/go2v (main) $ v run go2v.v  /workspaces/jacobin/src
converting "/workspaces/jacobin/src/classloader/classes.go" -> "/workspaces/jacobin/src/classloader/classes.v"
/workspaces/jacobin/src/classloader/classes.v:13:4: error: unexpected token `&`, expecting name
   11 | value_str string
   12 | value_func 
   13 | cp &CPool
      |    ^
   14 | }
   15 | const (
cli execution error: Generated output could not be formatted:
```

**Comment by Hunam6** [comment]
Thanks for the report, it should be fixed in [b941d60](https://github.com/vlang/go2v/commit/b941d606d51fd45a648a867dc21d7ded7d6413cc), please confirm it.

**Comment by Thihup** [comment]
@Hunam6 well I think this issue was resolved. Now there are others, do you think I should report it here or just wait and report in the future?
If you could take a look at the Jacobin project you could see more issues and maybe fix them :)

**Comment by JalonSolov** [comment]
There are still a _lot_ of issues.  go2v is not ready for full project conversion.

**Comment by Thihup** [comment]
Oh! Sorry for the misunderstanding. :)

**Comment by Hunam6** [comment]
Well, it's very simple to get issues to fix, just run Go2V on any Go std lib or Go project and here you go. So if you have a precise or even better, already investigated, issue like the one you reported that's good otherwise it's useless.
