### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by shyamsundarb-arch** [vlang/go2v#85]
When I clone this repo and run "v run .", I get an error. 

Steps to reproduce:
1. Install V - version (V 0.2.4 a3c0a9b)
2. clone this repo
3. run the command "v run ."

Expectation:
For the V program to compile

Actual:
You get a compiler error. 

```bash
➜ v run . 
transpiler/ast_parser.v:162:21: error: infix expr: cannot use `int literal` (right expression) as `transpiler.Tree`  (you can use it inside an `unsafe` block)
  160 |             }
  161 |             .tree_close {
  162 |                 if current_tree.parent != 0 {
      |                                 ~~~~~~~~~~~
  163 |                     current_tree = current_tree.parent
  164 |                 }
```

**Comment by JalonSolov** [comment]
This is due to a recent change in V.  We'll need to get go2v updated to match.

**Comment by medvednikov** [comment]
@Hunam6 can you add go2v to V's ci.yml?

**Comment by shyamsundarb-arch** [comment]
> This is due to a recent change in V. We'll need to get go2v updated to match.

Is there anyway I can help? I want to, just need some references to understand the changes to be made.

**Comment by Hunam6** [comment]
> > This is due to a recent change in V. We'll need to get go2v updated to match.
> 
> Is there anyway I can help? I want to, just need some references to understand the changes to be made.

I'm sorry I did the fix as it was really small. Whatever, thank you for your interest in participating!

**Comment by Hunam6** [comment]
> @Hunam6 can you add go2v to V's ci.yml?

This was already added, but has been commented for now because of the CI breaking because of https://github.com/vlang/v/issues/14262.
