### ISSUE TITLE
parsing of invalid go code

### ISSUE THREAD

**Issue by osborngh** [vlang/go2v#86]
The parsing of invalid go code like
```go
package main

import "fmt"

func main() {
        fmt.Println("Does not work")
        return 1, 2, 3
}
```
returning multiple values from main function is not valid go but gets transpiled anyway

**Comment by medvednikov** [comment]
should just run the go compiler first to make sure it compiles

**Comment by JalonSolov** [comment]
Go is run to generate an AST, so it seems to parse just fine.  The transpiled V code, though, will barf.

**Comment by Hunam6** [comment]
As @JalonSolov explained, Go is responsible to generate the AST and preventing it from generating if there was an error, consequently I think that this is out of the scope of Go2V.
